baseURL = "/"
title = "Robert Walpole & Partners"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Robert Walpole and Partners" # title for frontpage, may include image
copyright = "RWP"
description = 'Expert Civil and Structural Engineers. Founded in 1968.'
startbuttonText = "Example Button"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Complete Technical Service'
body = '''
Robert Walpole and Partners (RWP) are engaged in a wide range of engineering works for a plethora of big boi clients.
I can put the client logos underneath here, such as London Underground, Affinity water etc.'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "London Underground"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Affinity Water"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "The Ham Group"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Experienced Engineers'
body = 'We are hiring design and senior design engineers.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Graduate Careers'
body = 'RWP currently has vacancies for graduate engineers to join our team in Slough. We accept graduates with at least a 2:1 MEng in Civil Engineering.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Student Placements'
body = 'We offer industrial placement years and summer placements.'

[params.three]
enable = true
title = 'Case Studies'
body = '''
We offer a wide range of services ranging from local projects to major national work.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Barrow Hill Reservoir"
body = "Structural design support for installation of a new inlet main around a reservoir chamber and related assets."

[[params.three.feature]]
icon = "fa-laptop"
title = "Taplow Footbridge"
body = "Detailed design of the bridge substructure and foundations up to platform level."

[[params.three.feature]]
icon = "fa-code"
title = "Crossrail Operational Signage"
body = "Detailed design of all operational signage on Crossrail route between West Drayton and Maidenhead."

[[params.three.feature]]
icon = "fa-headphones"
title = "London Underground Buried Service Surveys"
body = "Comprehensive buried services surveys on London Underground’s deep tube network utilising several technologies."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Really try..."
body = "... to find some more interesting projects than these."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Or if there aren't better projects..."
body = "... then don't include them."

[params.cta]
enable = true
title = "Company Policies"
body = "View our company policies and capability statement."


[[params.cta.link]]
href = "#"
text = "Policies"
special = false

[[params.cta.link]]
href = "#"
text = "Capability Statement"
special = true

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
